name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # oder deine Python-Version

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip

      - name: Tests ausführen
        run: |
          python -m unittest discover
